from __future__ import annotations

import unittest

from app.api.routes import dashboard


class DashboardTests(unittest.TestCase):
    def test_dashboard_uses_bootstrap_and_core_widgets(self) -> None:
        html = dashboard()
        self.assertIn("bootstrap@5.3.8", html)
        self.assertIn('id="balanceValue"', html)
        self.assertIn('id="profitCard"', html)
        self.assertIn("animateMetric", html)
        self.assertIn("profit-positive", html)
        self.assertIn('id="signalBadge"', html)
        self.assertIn('id="nearestSupport"', html)
        self.assertIn('id="nearestResistance"', html)
        self.assertIn('id="bosBadge"', html)
        self.assertIn('id="chochBadge"', html)
        self.assertIn('id="tradePlan"', html)
        self.assertIn('id="positionsBody"', html)
        self.assertIn('id="historyBody"', html)
        self.assertIn("/trade-history?days=3650", html)
        self.assertIn('id="recommendationBadge"', html)
        self.assertIn("Total Profit", html)
        self.assertIn("Total Loss", html)
        self.assertIn('id="capitalChart"', html)
        self.assertIn("/capital-curve?days=3650", html)
        self.assertIn('id="capitalTooltip"', html)
        self.assertIn('id="capitalPlayBtn"', html)
        self.assertIn("playCapitalCurve", html)
        self.assertIn("Replay", html)
        self.assertIn("stepDelay=180", html)
        self.assertIn("ctx.roundRect", html)
        self.assertIn("Pertumbuhan:", html)
        self.assertIn("Urutan close terbaru ke terlama", html)
        self.assertIn("bootstrap-icons@1.11.3", html)
        self.assertIn("bi-robot", html)
        self.assertIn("bi-crosshair", html)
        self.assertIn("updateRealtimeClock", html)
        self.assertIn("refreshStatusRealtime", html)
        self.assertIn("Semua posisi MT5 pada seluruh simbol", html)
        self.assertIn('id="manualTradeModal"', html)
        self.assertIn("openManualTrade('BUY')", html)
        self.assertIn("executeManualTrade", html)
        self.assertIn('id="marketSelect"', html)
        self.assertIn('<option value="BTCUSD">BTCUSD</option>', html)
        self.assertIn('<option value="XAUUSD">XAUUSD</option>', html)
        self.assertIn("changeMarket", html)
        self.assertIn('id="bulkSlPrice"', html)
        self.assertIn('id="bulkTpPrice"', html)
        self.assertIn("executeBulkLevel('SL')", html)
        self.assertIn("executeBulkLevel('TP')", html)
        self.assertIn("/trade/confidence-auto/start", html)
        self.assertIn("/trade/confidence-auto/stop", html)
        self.assertIn("AUTO CONFIDENCE", html)
        self.assertIn('id="confidenceToggleBtn"', html)
        self.assertIn("toggleConfidenceAuto", html)
        self.assertIn('id="autoMarketBTC"', html)
        self.assertIn('id="autoMarketXAU"', html)
        self.assertIn("/trade/confidence-auto/markets", html)
        self.assertIn("changeAutoMarkets", html)
        self.assertIn("Kontrol Trading", html)
        self.assertIn("sweetalert2@11", html)
        self.assertIn("position:'top-end'", html)
        self.assertIn("Swal.fire", html)
        self.assertIn("Tambah Posisi Searah", html)
        self.assertIn("Posisi yang sedang aktif", html)
        self.assertIn("syncManualLot", html)
        self.assertIn("symbol==='BTCUSD'?0.05:0.01", html)
        self.assertIn('id="strategiesModal"', html)
        self.assertIn("showStrategies", html)
        self.assertIn("/strategies", html)
        self.assertIn("Aktif untuk Live Trading", html)
        self.assertIn("dataTables.bootstrap5.min.css", html)
        self.assertIn("dataTables.bootstrap5.min.js", html)
        self.assertIn("jquery-3.7.1.min.js", html)
        self.assertIn('id="historyTable"', html)
        self.assertIn("historyDataTable", html)
        self.assertIn("bi-trophy-fill", html)
        self.assertIn("CLOSE ${esc(d.type_str)}", html)
        self.assertEqual(html.count('id="updatedAt"'), 1)
        self.assertIn("bi-x-octagon-fill", html)
        self.assertIn("bi-graph-up-arrow", html)
        self.assertIn("bi-graph-down-arrow", html)
        self.assertIn("history-chip", html)
        self.assertIn("chip-net-positive", html)
        self.assertIn('id="accountLoginModal"', html)
        self.assertIn("loginAccount", html)
        self.assertIn("logoutAccount", html)
        self.assertIn("Password tidak disimpan", html)
        self.assertIn('id="themeToggleBtn"', html)
        self.assertIn("cycleTheme", html)
        self.assertIn("dashboard-theme", html)
        self.assertIn('data-theme="night"', html)
        self.assertIn('data-theme="light"', html)
        self.assertIn("refreshDashboard()", html)


if __name__ == "__main__":
    unittest.main()
