from __future__ import annotations

import unittest

from app.api.routes import dashboard


class DashboardTests(unittest.TestCase):
    def test_dashboard_uses_bootstrap_and_core_widgets(self) -> None:
        html = dashboard()
        self.assertIn("bootstrap@5.3.8", html)
        self.assertIn('id="balanceValue"', html)
        self.assertIn('id="profitCard"', html)
        self.assertIn("animateMetric", html)
        self.assertIn("profit-positive", html)
        self.assertIn('id="signalBadge"', html)
        self.assertIn('id="nearestSupport"', html)
        self.assertIn('id="nearestResistance"', html)
        self.assertIn('id="bosBadge"', html)
        self.assertIn('id="chochBadge"', html)
        self.assertIn('id="tradePlan"', html)
        self.assertIn('id="positionsBody"', html)
        self.assertIn('id="historyBody"', html)
        self.assertIn('id="historyPeriodFilter"', html)
        self.assertIn('id="historyResultFilter"', html)
        self.assertIn('id="hourPeriodFilter"', html)
        self.assertIn('id="hourResultFilter"', html)
        self.assertIn("changeHistoryFilter", html)
        self.assertIn("changeHistoryFilter('hour')", html)
        self.assertIn("changeHistoryFilter('history')", html)
        self.assertIn("periodLabels", html)
        self.assertIn("resultLabels", html)
        self.assertIn("syncHistoryFilterControls", html)
        self.assertIn("currentHistoryQuery", html)
        self.assertIn("result=${encodeURIComponent(historyResult)}", html)
        self.assertIn("/trade-history?${historyQuery}", html)
        self.assertIn("/trade-hour-analysis?${hourQuery}", html)
        self.assertIn("Laporan jam profit/loss", html)
        self.assertIn('id="recommendationBadge"', html)
        self.assertIn("Total Profit", html)
        self.assertIn("Total Loss", html)
        self.assertIn('id="capitalChart"', html)
        self.assertIn("/capital-curve?days=3650", html)
        self.assertIn('id="capitalTooltip"', html)
        self.assertIn('id="capitalPlayBtn"', html)
        self.assertIn("playCapitalCurve", html)
        self.assertIn("Replay", html)
        self.assertIn("stepDelay=180", html)
        self.assertIn("ctx.roundRect", html)
        self.assertIn("Pertumbuhan:", html)
        self.assertIn("Urutan close terbaru ke terlama", html)
        self.assertIn("bootstrap-icons@1.11.3", html)
        self.assertIn("bi-robot", html)
        self.assertIn("bi-crosshair", html)
        self.assertIn("updateRealtimeClock", html)
        self.assertIn("refreshStatusRealtime", html)
        self.assertIn("connection_stable", html)
        self.assertIn("Ping ${ping}", html)
        self.assertIn("setInterval(refreshStatusRealtime,1000)", html)
        self.assertIn("Akun lain tidak terpengaruh", html)
        self.assertIn('id="activeAccountBadge"', html)
        self.assertIn("Semua aksi hanya diterapkan ke akun yang sedang dipilih", html)
        self.assertIn("activeAccountLabel", html)
        self.assertIn('id="manualTradeModal"', html)
        self.assertIn("openManualTrade('BUY')", html)
        self.assertIn("executeManualTrade", html)
        self.assertIn('id="marketSelect"', html)
        self.assertIn('<option value="BTCUSD">BTCUSD</option>', html)
        self.assertIn('<option value="XAUUSD">XAUUSD</option>', html)
        self.assertIn("changeMarket", html)
        self.assertIn('id="openMarketsBody"', html)
        self.assertIn('id="openMarketsPanel"', html)
        self.assertIn('id="openMarketsToggle"', html)
        self.assertIn('data-bs-toggle="collapse"', html)
        self.assertIn("syncOpenMarketsToggle", html)
        self.assertIn('id="openMarketsCount"', html)
        self.assertIn('id="marketSearch"', html)
        self.assertIn("loadOpenMarkets", html)
        self.assertIn("renderOpenMarkets", html)
        self.assertIn("Confidence", html)
        self.assertIn("scanMarketConfidence", html)
        self.assertIn("scanVisibleMarketConfidence", html)
        self.assertIn('id="scanMarketConfidenceBtn"', html)
        self.assertIn("/signal?timeframe=M5&symbol=", html)
        self.assertIn("openMarketDashboard", html)
        self.assertIn("toggleAutoMarket", html)
        self.assertIn("/markets?only_open=true", html)
        self.assertIn('id="bulkSlPrice"', html)
        self.assertIn('id="bulkTpPrice"', html)
        self.assertIn("executeBulkLevel('SL')", html)
        self.assertIn("executeBulkLevel('TP')", html)
        self.assertIn("/trade/confidence-auto/start", html)
        self.assertIn("/trade/confidence-auto/stop", html)
        self.assertIn("AUTO CONFIDENCE", html)
        self.assertIn('id="confidenceToggleBtn"', html)
        self.assertIn("toggleConfidenceAuto", html)
        self.assertIn('id="autoMarketOptions"', html)
        self.assertIn("auto-market-checkbox", html)
        self.assertIn("auto-market-chip", html)
        self.assertIn("/trade/confidence-auto/markets", html)
        self.assertIn("changeAutoMarkets", html)
        self.assertIn("setAutoMarkets", html)
        self.assertIn("Kontrol Trading", html)
        self.assertIn("control-grid", html)
        self.assertIn("control-group-actions", html)
        self.assertIn("grid-template-columns:repeat(3,minmax(0,1fr))", html)
        self.assertIn(".control-group-actions { grid-column:1/-1; }", html)
        self.assertIn('id="hourAnalysisBody"', html)
        self.assertIn('id="hourRecommendation"', html)
        self.assertIn("renderHourAnalysis", html)
        self.assertIn("/trade-hour-analysis", html)
        self.assertIn("Market Dashboard", html)
        self.assertIn("Market Auto Confidence", html)
        self.assertIn("Aksi Trading", html)
        self.assertIn("sweetalert2@11", html)
        self.assertIn("position:'top-end'", html)
        self.assertIn("Swal.fire", html)
        self.assertIn("Tambah Posisi Searah", html)
        self.assertIn("Posisi yang sedang aktif", html)
        self.assertIn("syncManualLot", html)
        self.assertIn("upper.includes('BTCUSD')?btcMinimumLot", html)
        self.assertIn('id="strategiesModal"', html)
        self.assertIn("showStrategies", html)
        self.assertIn("/strategies", html)
        self.assertIn("Aktif untuk Live Trading", html)
        self.assertIn("dataTables.bootstrap5.min.css", html)
        self.assertIn("dataTables.bootstrap5.min.js", html)
        self.assertIn("jquery-3.7.1.min.js", html)
        self.assertIn('id="historyTable"', html)
        self.assertIn("historyDataTable", html)
        self.assertIn("bi-trophy-fill", html)
        self.assertIn("CLOSE ${esc(d.type_str)}", html)
        self.assertEqual(html.count('id="updatedAt"'), 1)
        self.assertIn("bi-x-octagon-fill", html)
        self.assertIn("bi-graph-up-arrow", html)
        self.assertIn("bi-graph-down-arrow", html)
        self.assertIn("history-chip", html)
        self.assertIn("summary-card-grid", html)
        self.assertIn("report-filter-panel", html)
        self.assertIn("report-callout", html)
        self.assertIn("chip-net-positive", html)
        self.assertIn('id="accountLoginModal"', html)
        self.assertIn("loginAccount", html)
        self.assertIn("logoutAccount", html)
        self.assertIn("Password dienkripsi oleh Windows", html)
        self.assertIn("Riwayat Akun Tersimpan", html)
        self.assertIn("selectSavedAccount", html)
        self.assertIn("Password tersimpan aman", html)
        self.assertIn('id="themeToggleBtn"', html)
        self.assertIn("cycleTheme", html)
        self.assertIn("dashboard-theme", html)
        self.assertIn('data-theme="night"', html)
        self.assertIn('data-theme="light"', html)
        self.assertIn("refreshDashboard()", html)
        self.assertIn('id="btcSlDistance"', html)
        self.assertIn('id="btcTpDistance"', html)
        self.assertIn('id="xauSlDistance"', html)
        self.assertIn('id="xauTpDistance"', html)
        self.assertIn("Stop Loss ($)", html)
        self.assertIn("Take Profit ($)", html)
        self.assertIn("/risk-config", html)
        self.assertIn('id="tradingSetupModal"', html)
        self.assertIn('id="setupConfidence"', html)
        self.assertIn('id="setupMaxPositions"', html)
        self.assertIn('id="setupTrailingEnabled"', html)
        self.assertIn("saveTradingSetup", html)
        self.assertIn("/trading-setup", html)
        self.assertIn('id="scalpBaseLot"', html)
        self.assertIn('id="scalpConfigSymbol"', html)
        self.assertIn('value="BTCUSD"', html)
        self.assertIn('value="XAUUSD"', html)
        self.assertIn('/scalping-setup?symbol=', html)
        self.assertIn('id="scalpBasketTarget"', html)
        self.assertIn('id="scalpDailyTarget"', html)
        self.assertIn("Target Profit Harian Scalping", html)
        self.assertIn('id="scalpDailyTargetEnabled"', html)
        self.assertIn("Target profit harian aktif", html)
        self.assertIn('id="scalpMaxLot"', html)
        self.assertIn('id="scalpCapitalRecommendation"', html)
        self.assertIn("rekomendasi modal minimum", html)
        self.assertIn("/scalping-setup", html)
        self.assertIn("Konfigurasi Counter Scalping M1", html)
        self.assertIn('id="strategySelect"', html)
        self.assertIn("Counter Basket Scalping M1", html)
        self.assertIn("changeStrategy", html)
        self.assertIn("/trade/strategy/", html)

    def test_auto_confidence_defaults_to_xauusd_only(self) -> None:
        from app.main import TradingBot

        self.assertEqual(TradingBot().auto_symbols, ["XAUUSD"])


if __name__ == "__main__":
    unittest.main()
